# 参考: https://ja.vitejs.dev/guide/static-deploy.html#github-pages

name: Deploy to Github Pages

run-name: Deploy to Github Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:  # NOTE: 手動でもデプロイできるようにしておく

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # TODO: バージョンは固定の方が安定して良さそう
          bun-version: latest

      - name: Install dependencies
        run: bun install
        working-directory: ./app

      - name: Build
        run: bun run build
        working-directory: ./app

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./app/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
