name: OWASP ZAP Scan

run-name: OWASP ZAP Scan

on:
  workflow_call:
    inputs:
      target-url:
        type: string
        required: true
        description: OWASP ZAP のスキャン対象ページ URL
    secrets:
      token:
        required: true
        description: GitHub トークン

jobs:
  scan:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Owasp Zap Baseline Scan
        uses: zaproxy/action-baseline@7c4deb10e6261301961c86d65d54a516394f9aed # v0.14.0
        with:
          target: ${{ inputs.target-url }}
          token: ${{ secrets.token }}
          cmd_options: '-a'
