name: Run Unit Test

run-name: Run Unit Test

on: push

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # TODO: バージョンは固定の方が安定して良さそう
          bun-version: latest

      - name: Install dependencies
        run: bun install
        working-directory: ./app

      - name: Run Unit Test
        run: bun test
        working-directory: ./app

      - run: echo "TEST_RESULT=hoge" >> "${GITHUB_ENV}"
        shell: bash